version: "3.9"
services:
  backend:
    build: ./backend
    container_name: face-backend
    ports:
      - "9000:9000"
    volumes:
      - ./data/faiss:/app/data/faiss
      - ./data/images:/app/data/images
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: face-frontend
    ports:
      - "4000:80"
    depends_on:
      - backend
    restart: unless-stopped